# Spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    username: root
    password: shine123456
    url: jdbc:mysql://139.9.177.188:3307/note?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver